# Usar la imagen oficial de Node.js
FROM node:18

# Establecer directorio de trabajo
WORKDIR /app

# Copiar los archivos de la aplicación
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Construir la aplicación para producción
RUN npm run build

# Exponer el puerto 3000
EXPOSE 3000

# Comando por defecto para servir la aplicación
CMD ["npm", "run", "preview"]
